module.exports = {
  LIBRARY: 'lib',
  SPA: 'spa',
  MPA: 'mpa',
  STAGE0: 'stage0',
  STAGE1: 'stage1',
  STAGE2: 'stage2',
  STAGE3: 'stage3',
  SASS: 'sass',
  LESS: 'less',
  VUE: 'vue',
  REACT: 'react',
  NO: 'no',
  YES: 'yes',
  JS: 'js',
  TS: 'ts',
};
